name: WordPress project deployment

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SERVER_USER: ${{ vars.SERVER_USER }}
  SERVER_IP: ${{ vars.SERVER_IP }}
  SERVER_PATH: ${{ vars.SERVER_PATH }}
  SERVER_PORT: ${{ vars.SERVER_PORT }}

jobs:
  build-composer:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install Composer Dependencies
        run: |
          composer update-prod

      - name: Save Composer Built cache
        uses: actions/cache@v3
        with:
          path: wp
          key: composer-build-cache-${{ github.run_number }}

  build-node:
    runs-on: ubuntu-22.04

    needs: [build-composer]

    steps:
      - name: Use Composer Built cache
        uses: actions/cache@v3
        with:
          path: wp
          key: composer-build-cache-${{ github.run_number }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm Dependencies
        run: |
          npm run install-prod --prefix wp/wp-content/themes/wis-test-theme
          rm -rf wp/wp-content/themes/wis-test-theme/node_modules

      - name: Save Node Built cache
        uses: actions/cache@v3
        with:
          path: wp
          key: composer-node-build-cache-${{ github.run_number }}

  deploy:
    runs-on: ubuntu-22.04

    needs: [build-composer, build-node]

    steps:
      - name: Use Node Built cache
        uses: actions/cache@v3
        with:
          path: wp
          key: composer-node-build-cache-${{ github.run_number }}

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n    StrictHostKeyChecking no" > ~/.ssh/config

      - name: Deploy via SSH
        run: |
          echo "Deploying to ${SERVER_USER}@${SERVER_IP}:${SERVER_PATH} -p ${SERVER_PORT}"
          ssh ${SERVER_USER}@${SERVER_IP} -p ${SERVER_PORT} mkdir -p ${SERVER_PATH}
          rsync -og \
          --rsh="ssh -p ${SERVER_PORT}" \
          --chown=${SERVER_USER} \
          --chmod=Dug=rwx,Fug=rw \
          --checksum \
          --recursive \
          --verbose \
          --compress \
          --links \
          --delete-after \
          --exclude ".git*" \
          --exclude "*/node_modules/" \
          --exclude "backups/" \
          --exclude "logs/*" \
          --exclude "wp-content/cache" \
          --exclude "wp-content/languages" \
          --exclude "wp-content/uploads" \
          --exclude "wp-config.php" \
          wp ${SERVER_USER}@${SERVER_IP}:${SERVER_PATH}

